Merge sorted arrays
alievaleila/java-course-turing pull request #2
Opened 2024-10-07 18:56 UTC by alievaleila

Merge sorted arrays

2024-10-07 19:06 UTC, sabuhihuseynov commented on src/main/java/az/edu/turing/customLinkedListImpl/MyLinkedList.java
> +    int size;
also declare private

2024-10-07 19:08 UTC, sabuhihuseynov commented on src/main/java/az/edu/turing/customLinkedListImpl/MyLinkedList.java
> +        public T getData() {
I think no need getter setters

2024-10-07 19:08 UTC, sabuhihuseynov commented on src/main/java/az/edu/turing/customLinkedListImpl/MyLinkedList.java
> +    public MyLinkedList<T> addHead(T data) {
return added data instead of linkedList itself

2024-10-07 19:09 UTC, sabuhihuseynov commented on src/main/java/az/edu/turing/customLinkedListImpl/MyLinkedList.java
> +    public MyLinkedList<T> addTail(T data) {
return added data instead of linkedList itself

2024-10-07 19:09 UTC, sabuhihuseynov commented on src/main/java/az/edu/turing/customLinkedListImpl/MyLinkedList.java
> +            return null;
use Optional instead of return null

2024-10-07 19:10 UTC, sabuhihuseynov commented on src/main/java/az/edu/turing/customLinkedListImpl/MyLinkedList.java
> +            return null;
use Optional instead of return null

2024-10-07 19:10 UTC, sabuhihuseynov commented on src/main/java/az/edu/turing/customLinkedListImpl/MyLinkedList.java
> +        if (head == tail) {
use size instead of compare nodes

2024-10-07 19:11 UTC, sabuhihuseynov commented on src/main/java/az/edu/turing/customLinkedListImpl/MyLinkedList.java
> +    public void insert(int index, T item) {
return inserted value, also make arguments final

2024-10-07 19:11 UTC, sabuhihuseynov commented on src/main/java/az/edu/turing/customLinkedListImpl/MyLinkedList.java
> +    public void update(int index, T item) {
return updated value, also make arguments final

2024-10-07 19:11 UTC, sabuhihuseynov commented on src/main/java/az/edu/turing/customLinkedListImpl/MyLinkedList.java
> +    public void delete(int index) {
return deleted value, also make arguments final

2024-10-07 19:17 UTC, sabuhihuseynov commented on src/main/java/az/edu/turing/customLinkedListImpl/MyLinkedList.java
> +    public boolean delete(T item) {
make argument item final

2024-10-07 19:18 UTC, sabuhihuseynov commented on src/main/java/az/edu/turing/customLinkedListImpl/MyLinkedList.java
> +//    @Override
why this implementation in comment?

2024-10-07 19:19 UTC, sabuhihuseynov commented on src/main/java/az/edu/turing/mergeSortedArrays/MergeSortedArrays.java
> +    public static void mergeSortedArrays(int[] nums1, int m, int[] nums2, int n) {
do we need send sizes as parameter in method? we can get this information by nums.lenght

2024-10-07 19:20 UTC, sabuhihuseynov commented on src/main/java/az/edu/turing/mergeSortedArrays/MergeSortedArrays.java
> +    public static void mergeSortedArrays(int[] nums1, int m, int[] nums2, int n) {
why return type is void? should be int[]

2024-10-07 19:21 UTC, sabuhihuseynov commented on src/main/java/az/edu/turing/mergeSortedArrays/MergeSortedArrays.java
> +            }
wrong implementation

2024-10-07 19:21 UTC, sabuhihuseynov commented on src/test/java/az/edu/turing/LinkedListTest.java
> +
delete extra space

2024-10-07 19:21 UTC, sabuhihuseynov commented on src/main/java/az/edu/turing/mergeSortedArrays/MergeSortedArrays.java
> +    public static void main(String[] args) {
leave a space please

2024-10-07 19:22 UTC, sabuhihuseynov requested changes
pls look

2024-10-08 09:18 UTC, alievaleila commented on src/main/java/az/edu/turing/customLinkedListImpl/MyLinkedList.java
> +//    @Override
I'd forgotten to delete

2025-12-28 15:05 UTC, merged